parser: "babel-eslint"

parserOptions:
  sourceType: module
  ecmaFeatures:
    modules: true
    jsx: true
    experimentalObjectRestSpread: true

extends:
  - ./rules/use-strict.yml
  - ./rules/react.yml
  - ./rules/react-a11y.yml
  - plugin:flowtype/recommended
  - prettier
  - prettier/flowtype
  - prettier/react

plugins:
  - prettier
  - flowtype

settings:
  flowtype:
    onlyFilesWithFlowAnnotation: true

env:
  es6: true
  node: true
  browser: true

rules:
  prettier/prettier:
    - error
    - printWidth: 80
      tabWidth: 2
      semi: true
      trailingComma: all
      bracketSpacing: true
      jsxBracketSameLine: false
      singleQuote: true
      parser: flow

  jsx-a11y/anchor-is-valid: [ warn,
      { components: [Link], specialLink: [to], aspects: [noHref, invalidHref, preferButton] }
  ]
  jsx-a11y/label-has-for: warn
  jsx-a11y/img-redundant-alt: off
  jsx-a11y/no-static-element-interactions: off
  jsx-a11y/click-events-have-key-events: warn

  react/prop-types: off
  react/jsx-filename-extension: off
  react/require-default-props: off
  react/prefer-stateless-function: off
  react/no-unused-prop-types: warn
  react/no-find-dom-node: off
  react/default-props-match-prop-types: off
